// Generated by gencpp from file hello_world/HelloWorldService.msg
// DO NOT EDIT!


#ifndef HELLO_WORLD_MESSAGE_HELLOWORLDSERVICE_H
#define HELLO_WORLD_MESSAGE_HELLOWORLDSERVICE_H

#include <ros/service_traits.h>


#include <hello_world/HelloWorldServiceRequest.h>
#include <hello_world/HelloWorldServiceResponse.h>


namespace hello_world
{

struct HelloWorldService
{

typedef HelloWorldServiceRequest Request;
typedef HelloWorldServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HelloWorldService
} // namespace hello_world


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello_world::HelloWorldService > {
  static const char* value()
  {
    return "48dff27f3c07dd8bff817d8eb36e2278";
  }

  static const char* value(const ::hello_world::HelloWorldService&) { return value(); }
};

template<>
struct DataType< ::hello_world::HelloWorldService > {
  static const char* value()
  {
    return "hello_world/HelloWorldService";
  }

  static const char* value(const ::hello_world::HelloWorldService&) { return value(); }
};


// service_traits::MD5Sum< ::hello_world::HelloWorldServiceRequest> should match 
// service_traits::MD5Sum< ::hello_world::HelloWorldService > 
template<>
struct MD5Sum< ::hello_world::HelloWorldServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello_world::HelloWorldService >::value();
  }
  static const char* value(const ::hello_world::HelloWorldServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_world::HelloWorldServiceRequest> should match 
// service_traits::DataType< ::hello_world::HelloWorldService > 
template<>
struct DataType< ::hello_world::HelloWorldServiceRequest>
{
  static const char* value()
  {
    return DataType< ::hello_world::HelloWorldService >::value();
  }
  static const char* value(const ::hello_world::HelloWorldServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello_world::HelloWorldServiceResponse> should match 
// service_traits::MD5Sum< ::hello_world::HelloWorldService > 
template<>
struct MD5Sum< ::hello_world::HelloWorldServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello_world::HelloWorldService >::value();
  }
  static const char* value(const ::hello_world::HelloWorldServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_world::HelloWorldServiceResponse> should match 
// service_traits::DataType< ::hello_world::HelloWorldService > 
template<>
struct DataType< ::hello_world::HelloWorldServiceResponse>
{
  static const char* value()
  {
    return DataType< ::hello_world::HelloWorldService >::value();
  }
  static const char* value(const ::hello_world::HelloWorldServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_WORLD_MESSAGE_HELLOWORLDSERVICE_H
