// Generated by gencpp from file hello_world/HelloWorldServiceResponse.msg
// DO NOT EDIT!


#ifndef HELLO_WORLD_MESSAGE_HELLOWORLDSERVICERESPONSE_H
#define HELLO_WORLD_MESSAGE_HELLOWORLDSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_world
{
template <class ContainerAllocator>
struct HelloWorldServiceResponse_
{
  typedef HelloWorldServiceResponse_<ContainerAllocator> Type;

  HelloWorldServiceResponse_()
    : world()  {
    }
  HelloWorldServiceResponse_(const ContainerAllocator& _alloc)
    : world(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _world_type;
  _world_type world;




  typedef boost::shared_ptr< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HelloWorldServiceResponse_

typedef ::hello_world::HelloWorldServiceResponse_<std::allocator<void> > HelloWorldServiceResponse;

typedef boost::shared_ptr< ::hello_world::HelloWorldServiceResponse > HelloWorldServiceResponsePtr;
typedef boost::shared_ptr< ::hello_world::HelloWorldServiceResponse const> HelloWorldServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello_world

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hello_world': ['/home/rddesmit/catkin_ws/src/hello_world/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1513be71362b0030e84cefa89ea12fe9";
  }

  static const char* value(const ::hello_world::HelloWorldServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1513be71362b0030ULL;
  static const uint64_t static_value2 = 0xe84cefa89ea12fe9ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_world/HelloWorldServiceResponse";
  }

  static const char* value(const ::hello_world::HelloWorldServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string world\n\
";
  }

  static const char* value(const ::hello_world::HelloWorldServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.world);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct HelloWorldServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_world::HelloWorldServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_world::HelloWorldServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "world: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.world);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_WORLD_MESSAGE_HELLOWORLDSERVICERESPONSE_H
