// Generated by gencpp from file hello_world/HelloWorldServiceRequest.msg
// DO NOT EDIT!


#ifndef HELLO_WORLD_MESSAGE_HELLOWORLDSERVICEREQUEST_H
#define HELLO_WORLD_MESSAGE_HELLOWORLDSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_world
{
template <class ContainerAllocator>
struct HelloWorldServiceRequest_
{
  typedef HelloWorldServiceRequest_<ContainerAllocator> Type;

  HelloWorldServiceRequest_()
    : hello()  {
    }
  HelloWorldServiceRequest_(const ContainerAllocator& _alloc)
    : hello(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hello_type;
  _hello_type hello;




  typedef boost::shared_ptr< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HelloWorldServiceRequest_

typedef ::hello_world::HelloWorldServiceRequest_<std::allocator<void> > HelloWorldServiceRequest;

typedef boost::shared_ptr< ::hello_world::HelloWorldServiceRequest > HelloWorldServiceRequestPtr;
typedef boost::shared_ptr< ::hello_world::HelloWorldServiceRequest const> HelloWorldServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello_world

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hello_world': ['/home/rddesmit/catkin_ws/src/hello_world/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa1e4c96cf56304cea7e883d117e24f3";
  }

  static const char* value(const ::hello_world::HelloWorldServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa1e4c96cf56304cULL;
  static const uint64_t static_value2 = 0xea7e883d117e24f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_world/HelloWorldServiceRequest";
  }

  static const char* value(const ::hello_world::HelloWorldServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string hello\n\
";
  }

  static const char* value(const ::hello_world::HelloWorldServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hello);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct HelloWorldServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_world::HelloWorldServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_world::HelloWorldServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "hello: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.hello);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_WORLD_MESSAGE_HELLOWORLDSERVICEREQUEST_H
