(cl:defpackage hello_world-srv
  (:use )
  (:export
   "HELLOWORLDSERVICE"
   "<HELLOWORLDSERVICE-REQUEST>"
   "HELLOWORLDSERVICE-REQUEST"
   "<HELLOWORLDSERVICE-RESPONSE>"
   "HELLOWORLDSERVICE-RESPONSE"
  ))

